# Makefile Help Section

.PHONY: help all clean clean_pdf clean_html clean_docx clean_all

BASENAME = IPBES_Data_and_Knowledge_Management_Policy_ver2.1

TEXSOURCES = $(wildcard *.tex)

TEXFILE = $(BASENAME).tex
PDFFILE = $(BASENAME).pdf
HTMLFILE = $(BASENAME).html
DOCXFILE = $(BASENAME).docx

# all: Clean everything, build PDF, HTML, DOCX, then clean intermediates
all:
	$(MAKE) clean_all
	$(MAKE) pdf
	$(MAKE) html
	$(MAKE) docx
	$(MAKE) clean

# help: Show a list of available make targets with descriptions
help:
	@echo "Available Makefile targets:"
	@grep -E '^#[ ]{1,}[a-zA-Z_-]+:' $(MAKEFILE_LIST) | sed 's/^#//'


# pdf: Build the PDF including glossary
pdf: $(PDFFILE)
$(PDFFILE): $(TEXSOURCES)
	@echo "�� Building PDF with glossary..."
	pdflatex -interaction=nonstopmode -file-line-error -synctex=1 "$(TEXFILE)"
	makeglossaries "$(BASENAME).glo"
	pdflatex -interaction=nonstopmode -file-line-error -synctex=1 "$(TEXFILE)"
	pdflatex -interaction=nonstopmode -file-line-error -synctex=1 "$(TEXFILE)"

# html: Generate HTML output from the TeX source using htlatex
html: $(HTMLFILE)
$(HTMLFILE): $(TEXSOURCES)
	@echo "�� Generating HTML (3-pass htlatex)..."
	htlatex "$(TEXFILE)" "xhtml,charset=utf-8" " -cunihtf -utf8"
	makeglossaries "$(BASENAME).glo"
	htlatex "$(TEXFILE)" "xhtml,charset=utf-8" " -cunihtf -utf8"
	htlatex "$(TEXFILE)" "xhtml,charset=utf-8" " -cunihtf -utf8"

# docx: Convert the HTML to DOCX using Pandoc
docx: $(DOCXFILE)
$(DOCXFILE): $(HTMLFILE)
	@echo "�� Converting HTML to DOCX..."
	pandoc "$(HTMLFILE)" -o "$(DOCXFILE)"

# clean_html: Remove temporary files generated by htlatex
clean_html:
	@echo "�� Cleaning up htlatex-generated files..."
	rm -f $(BASENAME).{aux,css,dvi,idv,lg,tmp,xref,4tc,4ct,out}
	rm -f $(BASENAME)[0-9]*.html

# clean_pdf: Remove temporary files generated by pdflatex
clean_pdf:
	@echo "�� Cleaning up pdflatex-generated files..."
	rm -f $(BASENAME).{aux,log,toc,out,lof,lot,synctex.gz,glo,gls,glg,ist,idx,ind,ilg,nav,snm,bbl,blg,fdb_latexmk,fls}

# clean_docx: Placeholder for cleaning up DOCX-related files
clean_docx:
	@echo "�� Cleaning up pdflatex-generated files..."

# clean: Remove all intermediate files but keep outputs
clean: clean_pdf clean_html
	@echo "�� Cleaning temporary files..."

# clean_all: Remove all outputs and intermediates
clean_all: clean 
	@echo "�� Cleaning all generated fieles files..."
	rm -f $(HTMLFILE)
	rm -f $(PDFFILE)
	rm -f $(DOCXFILE)

# printvars: Print all user-defined Makefile variables
printvars:
	@echo "�� Listing all Makefile variables:"
	@$(foreach v,$(.VARIABLES),\
		$(if $(filter-out environment% default automatic,$(origin $v)),\
		echo "$$v = $($v)";))
